### PR TITLE
Add PX4 acro rate curve

### LINKED ISSUE #4: Can I add PX4 acro rate parameters to your awsome tool?
**Story:** Recently we started FPV racing the PX4 flight control firmware on pixracer boards. See https://docs.px4.io/en/frames_multicopter/qav_r_5_kiss_esc_racer.html
It has a lot of features like failsafes, got a lot better in racing performance with airmode, ... and started to support the low cost Omnibus F4 board which stacks onto the 4in1 Hobbywing ESC board.

**Issue:** The parameters for acro mode which you use for racing are a bit different from e.g. KISS on PX4, it's easier to tune because the values are more independent: you set the maximal rate which stays afterwards and then just shape the curve using expo and superexpo. But the rate stays and superexpo does not screw up expo...

**Goal:** Your comparing/converting tool is awsome! Am I allowed to add PX4 rates and link it in the official documentation? It should not be complicated, the formula is quite straight forward: https://www.desmos.com/calculator/yze23xmpqc
I would have already made a PR but **I don't see where the apparently server side parameter conversions are done** https://github.com/apocolipse/RotorPirates/blob/master/js/RotorPirates.js#L74-L80 Is that closed source or am I just blind?

Thanks in advance!

### PR DESCRIPTION
**Pull request by MaEtUgR**
fixes #4

A pile of copy pasting and UI reordering later I added the PX4 acro mode rates implemented [here](https://github.com/PX4/Firmware/blob/573dd89cbfad6e389d7a10db20d4ac8a6ede682e/src/lib/mathlib/math/Functions.hpp#L78-L95) to the Python script of RotorPirates.

I also started adding it to the javascript part but honestly I stranded a bit because there's even more copy pasting and the javascript file used in the HTML is the one from online. Probably there should be a relative path and then local testing would work. @apocolipse any suggestions on that?

rotorpirates

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Awesome!

**Comment by MaEtUgR** [comment]
@apocolipse Can we get it in? Otherwise I'll close and document the PX4 rates in a different way.

**Comment by apocolipse** [comment]
> @apocolipse Can we get it in? Otherwise I'll close and document the PX4 rates in a different way.

If you can get the HTML and JS updated I'll merge this in, otherwise can leave it open if someone else wants to try it.  Once you do that I'll see about updating the proprietary side backend for conversion calculation.

**Comment by MaEtUgR** [comment]
I tried to dive into the web implementation. It's an independent reimplementation and too much effort in my eyes. I'll document in a different way. Thanks anyways.

**Pull request closed without merging**
